apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sensors.fullname" . }}
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
data:
  modules: |
  {{- toYaml .Values.sensors.modules | nindent 4 }}
{{- range $elem := .Values.sensors.modules }}
  {{ $elem.name }}: |
  {{- toYaml $elem | nindent 4 }}
{{- end}}
