apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sensors.fullname" . }}-rabbitmq
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
data:
  RABBITMQ_USERNAME: {{ .Values.sensors.rabbitmq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.sensors.rabbitmq.password | b64enc }}
type: Opaque
immutable: true