apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sensors.fullname" . }}-rabbitmq
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
data:
  RMQ_USERNAME: {{ .Values.settings.rabbitmq.username | b64enc }}
  RMQ_PASSWORD: {{ .Values.settings.rabbitmq.password | b64enc }}
type: Opaque
immutable: true