apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devices.sensors.io
spec:
  group: sensors.io
  scope: Namespaced
  names:
    plural: devices
    singular: device
    kind: Device
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              type:
                type: string
    selectableFields:
    - jsonPath: .spec.type
    additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
