apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.sensors.io
spec:
  group: sensors.io
  scope: Namespaced
  names:
    plural: modules
    singular: module
    kind: Module
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              type:
                type: string
              nodeName:
                type: string
              image:
                type: object
                properties:
                  repository:
                    type: string
                  tag:
                    type: string
              devices:
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    config:
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                      type: array
                type: array
    selectableFields:
    - jsonPath: .spec.type
    - jsonPath: .spec.nodeName
    additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .spec.nodeName
      name: Node
      type: string
