name: Publish docker image
description: ""

inputs:
  token:
    description: ""
    required: true
  registry:
    description: ""
    required: true
  repository_lc:
    description: ""
    required: true
  image-name:
    description: ""
    required: true
  tag-name:
    description: ""
    required: true
  working-directory:
    description: ""
    required: true
  build-args:
    description: ""
    default: ""
  platforms:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Print
      shell: bash
      run: echo "${{ toJSON(inputs) }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.working-directory }}/Dockerfile
        context: ${{ inputs.working-directory }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        provenance: false
        push: true
        tags: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.repository_lc }}/${{ inputs.image-name }}:${{ inputs.tag-name }}
