name: Publish

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'controller/**'
      - 'raspberrypi/**'
      - '.github/**'

jobs:
  build-and-push-controller:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: controller
      tag-name: ${{ github.ref_name }}
      working-directory: controller
    permissions:
      contents: read
      packages: write

  build-and-push-raspberrypi:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: raspberrypi
      tag-name: ${{ github.ref_name }}
      working-directory: raspberrypi
      platforms: linux/arm64
    permissions:
      contents: read
      packages: write
