name: Publish

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'controller/**'
      - 'module/**'
      - 'scripts/**'
      - '.github/**'

jobs:
  build-and-push-controller:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: controller
      tag-name: ${{ github.ref_name }}
      working-directory: controller
      platforms: ''
    permissions:
      contents: read
      packages: write

  build-and-push-raspberrypi3b:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: raspberrypi3b
      tag-name: ${{ github.ref_name }}
      working-directory: module/raspberrypi3b
      platforms: linux/arm64
    permissions:
      contents: read
      packages: write

  build-and-push-raspberrypi5:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: raspberrypi5
      tag-name: ${{ github.ref_name }}
      working-directory: module/raspberrypi5
      platforms: linux/arm64
    permissions:
      contents: read
      packages: write